name: Enhancement
description: An improvement to something that already exists on the site.
title: "[Enhancement]: "
labels: ["Enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: where
    attributes:
      label: Where is the content or feature you'd like to improve?
      description: Provide any relevant URLs.
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What is the improvement you would like to see?
      description: Provide as much detail as you can.
    validations:
      required: true
