name: Feature
description: A new addition to the site - a page, component, or content.
title: "[Feature]: "
labels: ["Feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: where
    attributes:
      label: Where would this new content or feature live?
      description: Please provide any relevant URLs.
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Please describe the new content or feature you would like to see on the site.
    validations:
      required: true
