name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-synonyms: '{"Priority:Critical":["How urgent is this bug? Critical"],"Priority:Critical":["How urgent is this bug? Low"],"question":["help"]}'
          labels-not-allowed: '["Content","duplicate","good first issue","help wanted","invalid","jira","question","Schedules","Status: Complete","Status: Confirmed","Status: Feedback Needed","Status: In Progress","Status: On Hold","Status: Review Needed","Trip Planner","wontfix"]'
